{
    "TEAM"
    "Team_id":"22902d"
    "Team_Name":"DELTA_CITY_ENFORCERS"
    "MASCOT":"ROBOLAD"
    "PLAYERS":[
        {
            "Player_ID":"1400"
            "FIRST_NAME":"ALEX"
            "LAST_NAME":"MURPHY"
        }
        ...
        {
            "Player_ID":"4677"
            "FIRST_NAME":"CLARENCE"
            "LAST_NAME":"BODDICKER"
        }
        ...
        {
            "Player_ID":"2445"
            "FIRST_NAME":"DICK"
            "LAST_NAME":"JONES"
        }
        ...
        {
            "Player_ID":"5237"
            "FIRST_NAME":"BOB"
            "LAST_NAME":"MORTON"
        }
    ]
}
